### ISSUE TITLE
error while following importLPFDemo steps

### ISSUE THREAD

**Issue by cuong450** [taborlab/Iris#306]
Printed Error:
/Desktop/Iris-master/Python/LPFParser.py", line 207, in plotLPFData
    plt.step(data[0]/1000./60., data[1][:,r,c,chi], lw=mplargs['lw'], alpha=mplargs['alpha'],

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

<matplotlib.figure.Figure at 0x1820ea4f28>

Hi, Do you have any suggestions on why this would occur? Thank you.

**Comment by SynbioLucas** [comment]
The proximal cause of the error is, as the message says, a float is being passed to the `data` numpy array as an index, likely `r`, which is calculated a few lines above. Unfortunately, however, I am not able to replicate this error myself.

- Did you modify the code in `importLPFDemo` in any way that might have caused this? Type errors like this should be caught by the `plotLPFData` function, but that could explain why I'm not seeing the error.
- Which code were you trying to run that produced this error? The entire Notebook runs fine for me.
- I assume there were no other errors reported earlier in the notebook?
- Which version of Python are you running? I could see this being caused by trying to run this code in Python 3. Know that it was developed in Python 2.7 (which is dramatically different), and Python 3 is not supported at this time.
- What version of numpy are you using?
- Can you provide the full stack trace? (error output)

Note that this appears to only be a problem in the plotting function `plotLPFData`. If you do not need this functionality, and are just interested in parsing the LPF file into an array, you can move on until we find a solution.

**Comment by cuong450** [comment]
- Which version of Python are you running? I could see this being caused by trying to run this code in Python 3. Know that it was developed in Python 2.7 (which is dramatically different), and Python 3 is not supported at this time.

Issue RESOLVED when I switched to 2.7.14, originally I was running with Python 3.x
